port 1194
proto tcp-server
dev-type tun
topology subnet
server 10.67.0.0 255.255.0.0

ca /etc/openvpn/pki/ca.crt
cert /etc/openvpn/pki/server.crt
key /etc/openvpn/pki/server.key
dh none
tls-version-min 1.2
tls-cert-profile preferred
tls-crypt /etc/openvpn/pki/tls-crypt.key
verify-client-cert none
username-as-common-name
auth-user-pass-verify /usr/local/bin/ket-openvpn-auth via-file
script-security 2

data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305
data-ciphers-fallback AES-256-GCM
auth SHA256
allow-compression no

push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 1.0.0.1"
push "block-ipv6"

keepalive 10 60
reneg-sec 300
tcp-nodelay
persist-key
persist-tun
user nobody
group nogroup
verb 3
mute 10
