foreground = yes
syslog = no
debug = notice
sslVersionMin = TLSv1.2

[ket-openvpn]
accept = 0.0.0.0:8447
connect = openvpn-agent:1194
cert = /etc/stunnel/tls/fullchain.pem
key = /etc/stunnel/tls/privkey.pem
